import {
  Home,
  AddPhotoAlternate,
  AddShoppingCart,
  AutoAwesomeMotion,
  MenuBook,
  Dashboard,
  Android,
  Apple,
  LocalGroceryStore,
  BugReport,
  PersonAdd,
  Assessment,
  Add,
  PendingActions,
  PowerSettingsNew,
  RecentActors,
  Waves,
  Person,
  PlaylistRemove,
  Groups,
  Adjust,
  Article,
  Build,
  ManageAccounts,
  ManageHistory,
  Check,
  Search,
  Delete,
  Edit,
  Close
} from '@mui/icons-material';

const registerIcons = {
  Dashboard: () => <Dashboard />,
  Home: () => <Home />,
  AddPhotoAlternate: () => <AddPhotoAlternate />,
  AddShoppingCart: () => <AddShoppingCart />,
  MenuBook: () => <MenuBook />,
  AutoAwesomeMotion: () => <AutoAwesomeMotion />,
  Android: () => <Android />,
  Apple: () => <Apple />,
  LocalGroceryStore: () => <LocalGroceryStore />,
  BugReport: () => <BugReport />,
  PersonAdd: () => <PersonAdd />,
  Assessment: () => <Assessment />,
  Add: () => <Add sx={{ width: 36, height: 36 }} />,
  PendingActions: () => <PendingActions sx={{ width: 36, height: 36 }} />,
  PowerSettingsNew: () => <PowerSettingsNew />,
  RecentActors: () => <RecentActors />,
  Waves: () => <Waves />,
  Person: () => <Person />,
  PlaylistRemove: () => <PlaylistRemove />,
  Groups: () => <Groups />,
  Adjust: () => <Adjust />,
  Article: () => <Article />,
  Build: () => <Build />,
  ManageAccounts: () => <ManageAccounts />,
  ManageHistory: () => <ManageHistory />,
  Check: () => <Check />,
  Search: () => <Search />,
  Delete: () => <Delete />,
  Edit: () => <Edit />,
  Close: () => <Close />
};

export default registerIcons;
