export const GET_ALL_GROUP = 'GET_ALL_GROUP';
export const CREATE_GROUP = 'CREATE_GROUP';
export const GET_GROUP_ID = 'GET_GROUP_ID';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const RESET_GROUP_RECORD = 'RESET_GROUP_RECORD';
export const GET_ALL_USER_IN_GROUP = 'GET_ALL_USER_IN_GROUP';
