export const GET_ALL_PERMISSION = 'GET_ALL_PERMISSION';
export const CREATE_PERMISSION = 'CREATE_PERMISSION';
export const GET_PERMISSION_ID = 'GET_PERMISSION_ID';
export const UPDATE_PERMISSION = 'UPDATE_PERMISSION';
export const RESET_PERMISSION_RECORD = 'RESET_PERMISSION_RECORD';
