export const GET_ALL_ROLE = 'GET_ALL_ROLE';
export const CREATE_ROLE = 'CREATE_ROLE';
export const GET_ROLE_ID = 'GET_ROLE_ID';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const RESET_ROLE_RECORD = 'RESET_ROLE_RECORD';
export const GET_ALL_USER_IN_ROLE = 'GET_ALL_USER_IN_ROLE';
export const GET_ALL_PERMISSION_IN_ROLE = 'GET_ALL_PERMISSION_IN_ROLE';
